name: snibbo_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  dio: ^5.8.0+1
  toastification: ^3.0.2
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  persistent_bottom_nav_bar: ^6.2.1
  flutter_slidable: ^4.0.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.11.0
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  flutter_staggered_grid_view: ^0.7.0
  story_view: ^0.16.5
  get_it: ^8.0.3
  pro_image_editor: ^9.7.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  flutter_image_compress: ^2.4.0
  path: ^1.9.1
  image_editor_plus: ^1.0.6
  shimmer: ^3.0.0
  timeago: ^3.7.1
  line_icons: ^2.0.3
  lucide_icons: ^0.257.0
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  emoji_picker_flutter: ^4.3.0
  flutter_keyboard_visibility: ^6.0.0
  socket_io_client: ^3.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

  fonts:
    - family: poppinsBold
      fonts:
        - asset: "assets/Poppins-bold.ttf"

